import place1 from "../assets/png/place1.png";
import place2 from "../assets/png/place2.png";
import place3 from "../assets/png/place3.png";

export const ACTIVITY = [
  {
    activityName: "Soothing Bhutan Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place1,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "multi day",
  },
  {
    activityName: "Hypnotizing Himachel Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place2,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "multi day",
  },
  {
    activityName: "Mind Blowing Goa Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place3,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "multi day",
  },
  {
    activityName: "Soothing Bhutan Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place1,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "hourly",
  },
  {
    activityName: "Hypnotizing Himachel Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place2,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "hourly",
  },
  {
    activityName: "Mind Blowing Goa Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place3,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "hourly",
  },
  {
    activityName: "Soothing Bhutan Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place1,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "single day",
  },
  {
    activityName: "Hypnotizing Himachel Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place2,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "single day",
  },
  {
    activityName: "Mind Blowing Goa Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place3,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "single day",
  },
];
