import place1 from "../assets/png/place1.png";
import place2 from "../assets/png/place2.png";
import place3 from "../assets/png/place3.png";
import event from "../assets/png/event.png";
import retreat from "../assets/png/retreat.png";

export const ACTIVITY = [
  {
    activityName: "Soothing Bhutan Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place1,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "multi day",
  },
  {
    activityName: "Hypnotizing Himachel Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place2,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "multi day",
  },
  {
    activityName: "Mind Blowing Goa Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place3,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "multi day",
  },
  {
    activityName: "Soothing Bhutan Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place1,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "hourly",
  },
  {
    activityName: "Hypnotizing Himachel Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place2,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "hourly",
  },
  {
    activityName: "Mind Blowing Goa Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place3,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "hourly",
  },
  {
    activityName: "Soothing Bhutan Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place1,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "single day",
  },
  {
    activityName: "Hypnotizing Himachel Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place2,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "single day",
  },
  {
    activityName: "Mind Blowing Goa Tour Package",
    duration: "4 Days 3 Nights",
    cities: "Rumto (1D) Teads (3D)",
    offerBy: "TexaTrove",
    otherDetails: "Multiple departures ( 23 May - 28 May )",
    imgUrl: place3,
    rating: 4,
    review: "89 Reviews",
    price: 16949,
    type: "single day",
  },
];

export const EVENT = [
  {
    name: 'Stand-up Comedy For A Cause "Atul Khatri\'s The 10 PM Show"',
    datetime: "May 27 | 10 pm",
    type: "Online",
    price: 499,
    imgUrl: event,
  },
  {
    name: 'Stand-up Comedy For A Cause "Atul Khatri\'s The 10 PM Show"',
    datetime: "May 27 | 10 pm",
    type: "Online",
    price: 499,
    imgUrl: event,
  },
  {
    name: 'Stand-up Comedy For A Cause "Atul Khatri\'s The 10 PM Show"',
    datetime: "May 27 | 10 pm",
    type: "Online",
    price: 499,
    imgUrl: event,
  },
  {
    name: 'Stand-up Comedy For A Cause "Atul Khatri\'s The 10 PM Show"',
    datetime: "May 27 | 10 pm",
    type: "Offline",
    price: 499,
    imgUrl: event,
  },
  {
    name: 'Stand-up Comedy For A Cause "Atul Khatri\'s The 10 PM Show"',
    datetime: "May 27 | 10 pm",
    type: "Offline",
    price: 499,
    imgUrl: event,
  },
  {
    name: 'Stand-up Comedy For A Cause "Atul Khatri\'s The 10 PM Show"',
    datetime: "May 27 | 10 pm",
    type: "Offline",
    price: 499,
    imgUrl: event,
  },
];

export const RETREAT = [
  {
    name: "200 Hour 6 Month Online Yin Yoga Therapy Teacher Training",
    duration: "7 Days",
    type: "Online",
    price: 16999,
    imgUrl: retreat,
    language: "english",
  },
  {
    name: "200 Hour 6 Month Online Yin Yoga Therapy Teacher Training",
    duration: "7 Days",
    type: "Online",
    price: 16999,
    imgUrl: retreat,
    language: "english",
  },
  {
    name: "200 Hour 6 Month Online Yin Yoga Therapy Teacher Training",
    duration: "7 Days",
    type: "Online",
    price: 16999,
    imgUrl: retreat,
    language: "english",
  },
  {
    name: "200 Hour 6 Month Online Yin Yoga Therapy Teacher Training",
    duration: "7 Days",
    type: "Offline",
    price: 16999,
    imgUrl: retreat,
    language: "english",
  },
  {
    name: "200 Hour 6 Month Online Yin Yoga Therapy Teacher Training",
    duration: "7 Days",
    type: "Offline",
    price: 16999,
    imgUrl: retreat,
    language: "english",
  },
  {
    name: "200 Hour 6 Month Online Yin Yoga Therapy Teacher Training",
    duration: "7 Days",
    type: "Offline",
    price: 16999,
    imgUrl: retreat,
    language: "english",
  },
];
